package Coversion_Units;
import java.util.*;
public class Convesions {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//This code is Auto Generated by eclipse
		Scanner sc= new Scanner(System.in);
		int n= sc.nextInt();
		int A[][]= new int[n][n];
		
		for(int i=0; i<n; i++)
		{
			for(int j=0; j<n;j++)
			{
				A[i][j]= sc.nextInt();
			}
		}
		int sum=0;
		int Ans=0;
		int x= sc.nextInt();
		
		for(int i=0; i<n; i++)
		{
			for(int j=0; j<n;j++)
			{
				if(A[i][j]== x)
				{
					sum= i+j+2;
				}
			}
		}
		
		if(sum%2==0)
		{
			for(int i=0; i<n; i++)
			{
				for(int j=0; j<n;j++)
				{
					if(A[i][j]%2==0)
					{
						Ans= Ans+ A[i][j];
					}
				}
			}
		}
		else
		{
			for(int i=0; i<n; i++)
			{
				for(int j=0; j<n;j++)
				{
					if(A[i][j]%2!=0)
					{
						Ans= Ans+ A[i][j];
					}
				}
			}
		}
		
		System.out.println(Ans);
	}

}